apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
      - name: conv-api
        image: antonlarichev/conv-api:1.0
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
        env:
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: AMQP_PASSWORD
          valueFrom:
             secretKeyRef:
               name: rabbitmq-secret
               key: RABBITMQ_DEFAULT_PASS
        - name: AMQP_EXCHANGE
          value: demo-exchange
        - name: AMQP_HOSTNAME
          value: rabbitmq-clusterip
        volumeMounts:
            - name: conv-api-data
              mountPath: /opt/app/uploads
      volumes:
         - name: conv-api-data
           persistentVolumeClaim:
             claimName: conv-api-pvc